### ISSUE TITLE
Android 11 対応

### ISSUE THREAD

**Issue by shibafu528** [shibafu528/Yukari#283]
https://developer.android.com/about/versions/11?hl=ja

## TODO
- [x] targetSdkVersion = 30
- [x] [Scoped storage](https://developer.android.com/about/versions/11/privacy/storage?hl=ja)
  - 設定のインポート・エクスポートに影響 (`/sdcard/Yukari4a`)
  - アプリのアンインストールの影響を受けないためにこうしていたが、さてどうしたことか……
  - 一旦targetSdkVersion = 29でScoped storageをオプトアウトしてリリースすれば、移行の時間を稼げる
- [x] [Toast APIの機能縮小](https://developer.android.com/about/versions/11/behavior-changes-11?hl=ja#text-toast-api-changes)
  - setGravityが機能しなくなる
- [x] [自分以外のパッケージの情報が隠されるようになった](https://developer.android.com/about/versions/11/privacy/package-visibility?hl=ja)
  - 今まで通りに `queryIntentActivities` などでパッケージ情報をクエリしても、自分のパッケージ内のものしか返ってこなくなる。
  - twicca pluginのクエリと、`shibafu.yukari.ACTION_LINK_ACCEL` に影響。

**Comment by shibafu528** [comment]
ACTION_OPEN_DOCUMENT_TREE で読み書きするディレクトリを指定してもらうしかない？

**Comment by shibafu528** [comment]
2021年11月からは targetSdkVersion >= 30 必須。  
https://android-developers.googleblog.com/2020/11/new-android-app-bundle-and-target-api.html

**Comment by shibafu528** [comment]
Scoped storage対応は数年前のコミットでSAFをなるべく使うようにして対応済。  
mruby pluginがファイルを開いている場合については知らないことにする。

**Comment by shibafu528** [comment]
AndroidManifest.xmlへのIntent query列挙完了。たぶんこれだけだと思う。

**Comment by shibafu528** [comment]
## `Toast.setGravity`

以下の場所で使用されている。

- 投稿画面のプラグインボタン長押し→プラグイン名の表示
- クイック引用が有効化されている状態で引用ボタンを押した時→実行された引用方法の表示

どれも指の位置的にGravityが効いていないとほぼ見えないのだが、割と無くても困らなさそうなので放置する。
